package com.nexamart.backend.otp;

/** Sends a backend-generated OTP over SMS. */
public interface OtpSmsSender {

  /**
   * @param nationalPhone 10-digit Indian mobile number (already normalized)
   * @param otp           6-digit one-time password generated by this backend
   * @throws OtpProviderException when the provider rejected or could not process the request
   */
  void send(String nationalPhone, String otp);

  /** @return true when the provider credentials are present. */
  boolean isConfigured();
}
