package com.nexamart.backend.exception;
import jakarta.servlet.http.HttpServletRequest;import org.slf4j.Logger;import org.slf4j.LoggerFactory;import org.springframework.http.ResponseEntity;import org.springframework.orm.ObjectOptimisticLockingFailureException;
import org.springframework.dao.DataIntegrityViolationException;import org.springframework.web.bind.MethodArgumentNotValidException;import org.springframework.web.bind.annotation.ExceptionHandler;import org.springframework.web.bind.annotation.RestControllerAdvice;import org.springframework.web.multipart.MaxUploadSizeExceededException;import java.time.Instant;import java.util.Map;import java.util.UUID;
@RestControllerAdvice public class GlobalExceptionHandler{
 private static final Logger log=LoggerFactory.getLogger(GlobalExceptionHandler.class);
 @ExceptionHandler(ApiException.class) ResponseEntity<?> api(ApiException e){return ResponseEntity.status(e.status()).body(Map.of("message",e.getMessage(),"timestamp",Instant.now().toString()));}
 @ExceptionHandler(MethodArgumentNotValidException.class) ResponseEntity<?> validation(MethodArgumentNotValidException e){String m=e.getBindingResult().getFieldErrors().stream().findFirst().map(x->x.getField()+": "+x.getDefaultMessage()).orElse("Validation failed");return ResponseEntity.badRequest().body(Map.of("message",m,"timestamp",Instant.now().toString()));}
 @ExceptionHandler(MaxUploadSizeExceededException.class) ResponseEntity<?> uploadTooLarge(MaxUploadSizeExceededException e){return ResponseEntity.status(413).body(Map.of("message","Image is too large. Maximum 5 MB.","timestamp",Instant.now().toString()));}
 @ExceptionHandler(DataIntegrityViolationException.class) ResponseEntity<?> dataIntegrity(DataIntegrityViolationException e){log.warn("Data integrity conflict",e);return ResponseEntity.status(409).body(Map.of("message","The account details are already in use or conflict with existing data.","timestamp",Instant.now().toString()));}
 @ExceptionHandler(ObjectOptimisticLockingFailureException.class) ResponseEntity<?> conflict(ObjectOptimisticLockingFailureException e){return ResponseEntity.status(409).body(Map.of("message","The order was updated by another user. Refresh and try again.","timestamp",Instant.now().toString()));}
 @ExceptionHandler(Exception.class) ResponseEntity<?> generic(Exception e,HttpServletRequest request){String errorId=UUID.randomUUID().toString();log.error("Unhandled API error id={} method={} path={}",errorId,request.getMethod(),request.getRequestURI(),e);return ResponseEntity.internalServerError().body(Map.of("message","Something went wrong. Please try again.","errorId",errorId,"timestamp",Instant.now().toString()));}
}
