package com.nexamart.backend.service;

import com.nexamart.backend.api.ApiModels.LoginResponse;
import com.nexamart.backend.api.ApiModels.OtpSendResponse;
import com.nexamart.backend.config.AppProperties;
import com.nexamart.backend.domain.AccountStatus;
import com.nexamart.backend.domain.OtpChallenge;
import com.nexamart.backend.domain.Role;
import com.nexamart.backend.domain.UserAccount;
import com.nexamart.backend.exception.ApiException;
import com.nexamart.backend.otp.OtpProviderException;
import com.nexamart.backend.otp.OtpSmsSender;
import com.nexamart.backend.repository.OtpChallengeRepository;
import com.nexamart.backend.util.PhoneNumbers;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.UUID;

/**
 * Delivery-partner OTP login.
 *
 * <p>The OTP is generated by this backend (cryptographically secure), stored only as a salted
 * SHA-256 hash with an expiry, and delivered through {@link OtpSmsSender}. There is exactly one
 * OTP system — the provider never generates the code.
 */
@Service
public class PartnerOtpService {
  private static final Logger log = LoggerFactory.getLogger(PartnerOtpService.class);

  private final UserLookupService userLookup;
  private final OtpChallengeRepository challenges;
  private final AppProperties props;
  private final AuthService auth;
  private final OtpSmsSender smsSender;
  private final SecureRandom random = new SecureRandom();

  public PartnerOtpService(UserLookupService userLookup,
                           OtpChallengeRepository challenges,
                           AppProperties props,
                           AuthService auth,
                           OtpSmsSender smsSender) {
    this.userLookup = userLookup;
    this.challenges = challenges;
    this.props = props;
    this.auth = auth;
    this.smsSender = smsSender;
  }

  @Transactional
  public OtpSendResponse send(String raw) {
    String phone = PhoneNumbers.requireIndianMobile(raw);
    UserAccount user = requirePartnerAccount(phone,
        "Delivery partner not registered. Please create an account.");

    enforceRateLimits(phone);

    String otp = generateOtp();
    OtpChallenge challenge = new OtpChallenge();
    challenge.setPhone(phone);
    challenge.setOtpHash(hash(phone, otp));
    challenge.setExpiresAt(Instant.now().plusSeconds(props.getOtpTtlSeconds()));
    challenges.saveAndFlush(challenge);

    if (props.isOtpDevMode() && !smsSender.isConfigured()) {
      log.warn("OTP dev mode active - no SMS was sent. phone={}", PhoneNumbers.mask(phone));
      return new OtpSendResponse(true, "OTP generated in development mode.",
          props.getOtpTtlSeconds(), "DEV", otp);
    }

    try {
      smsSender.send(phone, otp);
    } catch (OtpProviderException e) {
      String errorId = UUID.randomUUID().toString();
      log.error("[ERROR_ID={}] OTP provider failed: reason={} status={} detail={} phone={} userId={}",
          errorId, e.reason(), e.providerHttpStatus(), e.providerDetail(),
          PhoneNumbers.mask(phone), user.getId(), e);
      // The challenge row must not survive a failed delivery.
      challenges.delete(challenge);
      throw new ApiException(e.reason().status(),
          e.reason().userMessage() + " (Error ID: " + errorId + ")");
    }

    return new OtpSendResponse(true, "OTP sent successfully.",
        props.getOtpTtlSeconds(), "SMS", null);
  }

  @Transactional
  public LoginResponse verify(String raw, String otp) {
    String phone = PhoneNumbers.requireIndianMobile(raw);
    if (otp == null || !otp.trim().matches("\\d{6}")) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "Enter the 6-digit OTP.");
    }
    String code = otp.trim();

    OtpChallenge challenge = challenges.findTopByPhoneOrderByCreatedAtDesc(phone).orElseThrow(() ->
        new ApiException(HttpStatus.BAD_REQUEST, "OTP not found. Please request a new OTP."));
    if (challenge.isVerified()) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "This OTP has already been used. Please request a new OTP.");
    }
    if (challenge.getExpiresAt().isBefore(Instant.now())) {
      throw new ApiException(HttpStatus.BAD_REQUEST, "OTP expired. Please request a new OTP.");
    }
    if (challenge.getAttempts() >= props.getOtpMaxVerifyAttempts()) {
      throw new ApiException(HttpStatus.TOO_MANY_REQUESTS, "Too many incorrect attempts. Please request a new OTP.");
    }

    challenge.setAttempts(challenge.getAttempts() + 1);
    boolean matches = MessageDigest.isEqual(
        challenge.getOtpHash().getBytes(StandardCharsets.UTF_8),
        hash(phone, code).getBytes(StandardCharsets.UTF_8));
    if (!matches) {
      challenges.saveAndFlush(challenge);
      throw new ApiException(HttpStatus.BAD_REQUEST, "Incorrect OTP. Please try again.");
    }

    challenge.setVerified(true);
    challenges.saveAndFlush(challenge);

    UserAccount user = requirePartnerAccount(phone, "Delivery partner account not found.");
    return auth.issueDeliveryPartnerSession(auth.touch(user));
  }

  private UserAccount requirePartnerAccount(String phone, String notFoundMessage) {
    UserAccount user = userLookup
        .findByPhonePreferringRole(phone, Role.DELIVERY_PARTNER)
        .orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, notFoundMessage));
    if (user.getRole() != Role.DELIVERY_PARTNER) {
      throw new ApiException(HttpStatus.NOT_FOUND,
          "This mobile number is not registered as a delivery partner.");
    }
    if (user.getStatus() != AccountStatus.ACTIVE) {
      throw new ApiException(HttpStatus.FORBIDDEN, "Account is not active. Please contact support.");
    }
    return user;
  }

  /** Backend-enforced resend cooldown and hourly cap — the Android UI is never the only guard. */
  private void enforceRateLimits(String phone) {
    Instant now = Instant.now();
    challenges.findTopByPhoneOrderByCreatedAtDesc(phone).ifPresent(prev -> {
      Instant allowedAt = prev.getCreatedAt().plusSeconds(props.getOtpResendCooldownSeconds());
      if (allowedAt.isAfter(now)) {
        long wait = Math.max(1, allowedAt.getEpochSecond() - now.getEpochSecond());
        throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,
            "Please wait " + wait + " seconds before requesting another OTP.");
      }
    });
    long lastHour = challenges.countByPhoneAndCreatedAtAfter(phone, now.minusSeconds(3600));
    if (lastHour >= props.getOtpMaxSendsPerHour()) {
      throw new ApiException(HttpStatus.TOO_MANY_REQUESTS,
          "Too many OTP requests. Please try again after an hour.");
    }
  }

  private String generateOtp() {
    return String.format("%06d", random.nextInt(1_000_000));
  }

  private String hash(String phone, String otp) {
    try {
      MessageDigest md = MessageDigest.getInstance("SHA-256");
      return java.util.HexFormat.of()
          .formatHex(md.digest((phone + ":" + otp).getBytes(StandardCharsets.UTF_8)));
    } catch (Exception e) {
      throw new IllegalStateException(e);
    }
  }
}
